const MAIN_FILMS_COUNT = 24;
const MAIN_FILMS_COUNT_ON_START = 5;
const MAIN_FILMS_COUNT_BY_BUTTON = 5;
const MOST_COMMENTED_FILMS_COUNT = 2;
const TOP_RATED_FILMS_COUNT = 2;
const ESCAPE_KEY = `Escape`;

export {MAIN_FILMS_COUNT, MOST_COMMENTED_FILMS_COUNT, TOP_RATED_FILMS_COUNT,
  MAIN_FILMS_COUNT_ON_START, MAIN_FILMS_COUNT_BY_BUTTON, ESCAPE_KEY};
