const filmsData = {
  titles: [
    `The Dance of Life`,
    `Made of each Other`,
    `Popeye meets Sinbad`,
    `Sagebrush trail`,
    `Santa Claus Conquers the Martians`,
    `The great Flamarion`,
    `The man with the golden arm`
  ],
  posters: [
    `made-for-each-other.png`,
    `popeye-meets-sinbad.png`,
    `sagebrush-trail.jpg`,
    `santa-claus-conquers-the-martians.jpg`,
    `the-dance-of-life.jpg`,
    `the-great-flamarion.jpg`,
    `the-man-with-the-golden-arm.jpg`,
  ],
  possibleRating: [1.0, 10.0],
  possibleYears: [1965, 2020],
  possibleDurations: [65, 190],
  genres: [`Drama`, `Fantastic`, `Melodrama`, `Horror`, `Thriller`],
  descriptions: [
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit`,
    `Cras aliquet varius magna, non porta ligula feugiat eget`,
    `Fusce tristique felis at fermentum pharetra`,
    `Aliquam id orci ut lectus varius viverra`,
    `Nullam nunc ex, convallis sed finibus eget sollicitudin eget ante`,
    `Phasellus eros mauris, condimentum sed nibh vitae, sodales efficitur ipsum`,
    `Sed blandit, eros vel aliquam faucibus, purus ex euismod diam, eu luctus nunc ante ut dui`,
    `Sed sed nisi sed augue convallis suscipit in sed felis. Aliquam erat volutpat`,
    `Nunc fermentum tortor ac porta dapibus. In rutrum ac purus sit amet tempus`,
  ],
  possibleComments: [1, 10],
};
